version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ml_api
      POSTGRES_USER: ml_api
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"